
fn success1() (String, int) !err {
    return "test", 20
}
fn success2() String !err {
    throw err
}

test "Success handlers" {
    let result = ""
    success1() -> (r1, r2) {
        result = r1 + r2
    }
    assert(result == "test20")
    result = "x"
    success2() -> r1 {
        result = r1
    }
    assert(result == "x")
}
